In [1]:
import pandas as pd

In [3]:

## URL to CSV

df=pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',
                 sep='\t')
df

,item_code,item_name,display_level,selectable,sort_sequence
0,AA0,All items - old base,0,T,2
1,AA0R,Purchasing power of the consumer dollar - old ...,0,T,399
2,SA0,All items,0,T,1
3,SA0E,Energy,1,T,374
4,SA0L1,All items less food,1,T,358
5,SA0L12,All items less food and shelter,1,T,361
6,SA0L12E,"All items less food, shelter, and energy",1,T,362
7,SA0L12E4,"All items less food, shelter, energy, and used...",1,T,363
8,SA0L1E,All items less food and energy,1,T,359
9,SA0L2,All items less shelter,1,T,360
10,SA0L5,All items less medical care,1,T,356
11,SA0LE,All items less energy,1,T,357
12,SA0R,Purchasing power of the consumer dollar,0,T,398
13,SA311,Apparel less footwear,1,T,364
14,SAA,Apparel,0,T,187
15,SAA1,Men's and boys' apparel,1,T,188
16,SAA2,Women's and girls' apparel,1,T,195
17,SAC,Commodities,1,T,365
18,SACE,Energy commodities,1,T,375
19,SACL1,Commodities less food,1,T,366
20,SACL11,Commodities less food and beverages,1,T,367
21,SACL1E,Commodities less food and energy commodities,1,T,368
22,SACL1E4,"Commodities less food, energy, and used cars a...",1,T,369
23,SAD,Durables,1,T,371
24,SAE,Education and communication,0,T,311
25,SAE1,Education,1,T,312
26,SAE2,Communication,1,T,320
27,SAE21,Information and information processing,2,T,324
28,SAEC,Education and communication commodities,1,T,372
29,SAES,Education and communication services,1,T,373
...,...,...,...,...,...
369,SS47015,"Gasoline, unleaded midgrade",4,T,224
370,SS47016,"Gasoline, unleaded premium",4,T,225
371,SS47021,"Motor oil, coolant, and fluids",4,T,231
372,SS48021,Vehicle parts and equipment other than tires,4,T,230
373,SS52051,Parking fees and tolls,4,T,240
374,SS53021,Intercity bus fare,3,T,245
375,SS53022,Intercity train fare,3,T,246
376,SS53023,Ship fare,3,T,247
377,SS53031,Intracity mass transit,3,T,249
378,SS5702,Inpatient hospital services,4,T,264
379,SS5703,Outpatient hospital services,4,T,265
380,SS61011,"Toys, games, hobbies and playground equipment",3,T,298
381,SS61021,Film and photographic supplies,3,T,291
382,SS61023,Photographic equipment,3,T,292
383,SS61031,Pet food,3,T,281
384,SS61032,"Purchase of pets, pet supplies, accessories",3,T,282
385,SS62011,Automobile service clubs,4,T,241
386,SS62031,"Admission to movies, theaters, and concerts",3,T,305
387,SS62032,Admission to sporting events,3,T,306
388,SS62051,Photographer fees,3,T,294
389,SS62052,Photo Processing,3,T,295
390,SS62053,Pet services,3,T,284
391,SS62054,Veterinarian services,3,T,285
392,SS62055,Rental of video discs and other media,3,T,276
393,SS68021,Checking account and other bank services,4,T,351
394,SS68023,Tax return preparation and other accounting fees,4,T,352
395,SSEA011,College textbooks,3,T,314
396,SSFV031A,Food at elementary and secondary schools,3,T,122
397,SSGE013,Infants' equipment,3,T,355
398,SSHJ031,Infants' furniture,3,T,165